# This is a basic workflow to help you get started with Actions

name: bootcampclass1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    runs-on: ubuntu-latest

    - name: Installing Node
      uses: action/setup-node@v2-beta
      with:
            node-version: 10 

    - name: installing surge
      run: npm install --global surge
    - name: deploying on surge
      run: ./ bootcampclasss1.surge.sh --token "0ba6bae0044636434c2847a0402b7047"

      
